{
 "title": "Master ISRI 2026 - Supervision Capteurs Météo",
 "tags": [
  "isri",
  "kafka",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Suivi des Températures par Ville (Brut vs Moyenne Lissée)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "capteur_temperature_celsius", "legendFormat": "{{ville}} - Température Réelle" },
    {
     "expr": "capteur_temperature_moyenne_celsius",
     "legendFormat": "{{ville}} - Moyenne Lissée"
    }
   ]
  },
  {
   "title": "Débit du Bus (Messages / min)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mpm" } },
   "targets": [
    {
     "expr": "rate(kafka_messages_received_total[1m]) * 60",
     "legendFormat": "msg/min"
    }
   ]
  },
  {
   "title": "Surveillance du Système - Flux de Logs en Direct (Loki)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"consommateurs\"}"
    }
   ]
  }
 ]
}