[SERVICE]
    Flush        2
    Daemon       Off
    Log_Level    debug
    HTTP_Server  On
    HTTP_Port    2020
    HTTP_Listen  0.0.0.0

[INPUT]
    Name             tail
    Path             /var/log/global_logs/consommateurs.log
    Tag              java.logs
    Refresh_Interval 2
    Read_from_Head   True

[OUTPUT]
    Name    loki
    Match   java.logs
    Host    loki
    Port    3100
    Labels  job=consommateurs