apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Utilise le nom du service réseau Docker
    isDefault: true
    editable: true

  - name: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000